In [1]:
#import the libraries
import pandas as pd
import numpy as np
import datetime

### Player Stats 
<br><i>Note: From <a href='https://www.kaggle.com/datasets/kendallgillies/nflstatistics'>Kaggle.com</a></i>

In [2]:
#Import the datasets 
qb = pd.read_csv(r'Game_Logs_Quarterback.csv')
rb = pd.read_csv(r'Game_Logs_Runningback.csv') 
wr = pd.read_csv(r'Game_Logs_Wide_Receiver_and_Tight_End.csv')

In [3]:
#Combine the datasets for one large one containing all skill position players
stats = pd.concat([qb, rb, wr], ignore_index = True )

In [4]:
#See the columns in the dataset 
stats.columns

Index(['Player Id', 'Name', 'Position', 'Year', 'Season', 'Week', 'Game Date',
       'Home or Away', 'Opponent', 'Outcome', 'Score', 'Games Played',
       'Games Started', 'Passes Completed', 'Passes Attempted',
       'Completion Percentage', 'Passing Yards', 'Passing Yards Per Attempt',
       'TD Passes', 'Ints', 'Sacks', 'Sacked Yards Lost', 'Passer Rating',
       'Rushing Attempts', 'Rushing Yards', 'Yards Per Carry', 'Rushing TDs',
       'Fumbles', 'Fumbles Lost', 'Longest Rushing Run', 'Receptions',
       'Receiving Yards', 'Yards Per Reception', 'Longest Reception',
       'Receiving TDs'],
      dtype='object')

In [5]:
qb.columns

Index(['Player Id', 'Name', 'Position', 'Year', 'Season', 'Week', 'Game Date',
       'Home or Away', 'Opponent', 'Outcome', 'Score', 'Games Played',
       'Games Started', 'Passes Completed', 'Passes Attempted',
       'Completion Percentage', 'Passing Yards', 'Passing Yards Per Attempt',
       'TD Passes', 'Ints', 'Sacks', 'Sacked Yards Lost', 'Passer Rating',
       'Rushing Attempts', 'Rushing Yards', 'Yards Per Carry', 'Rushing TDs',
       'Fumbles', 'Fumbles Lost'],
      dtype='object')

In [6]:
stats.fillna(value = 0, inplace = True )
qb.fillna(value = 0, inplace = True)

In [7]:
#select the columns we are going to use for each 
stats = stats[['Player Id', 'Name', 'Year', 'Season', 'Home or Away', 'Week','Game Date', 'Opponent', 'Outcome', 'Passing Yards', 'TD Passes', 'Rushing Yards', 'Rushing TDs', 'Receiving Yards', 'Receiving TDs' ]]
qb = qb[['Player Id', 'Name', 'Year', 'Season', 'Home or Away','Week','Game Date', 'Opponent', 'Outcome', 'Passing Yards', 'TD Passes', 'Rushing Yards', 'Rushing TDs', 'Ints', 'Passer Rating' ]]

In [8]:
tot_cols_stats = ['Rushing Yards', 'Receiving Yards', 'Passing Yards','Rushing TDs', 'Receiving TDs', 'TD Passes']
tot_cols_qb = ['Rushing Yards', 'Passing Yards','Rushing TDs', 'TD Passes'] #target the columns to turn to numerics 
for col in tot_cols_stats: 
    stats[col] = pd.to_numeric(stats[col], errors = 'coerce') #turn the columns to numerics 
for col in tot_cols_qb: 
    qb[col] = pd.to_numeric(qb[col], errors = 'coerce') 
total_yards_cols_st = stats[['Rushing Yards', 'Receiving Yards', 'Passing Yards']]
total_td_st = stats[['Rushing TDs', 'Receiving TDs', 'TD Passes']]
total_yards_cols_qb = qb[['Rushing Yards','Passing Yards']] #target the columns that we would like to add togther
total_td_qb = qb[['Rushing TDs', 'TD Passes']]
tot_yards_stat = total_yards_cols_st.sum(axis = 1) #add together for total yards
tot_td_stat = total_td_st.sum(axis = 1) #add together for total touchdowns 
tot_yards_qb = total_yards_cols_qb.sum(axis = 1) #add together for total yards
tot_td_qb = total_td_qb.sum(axis = 1) #add together for total touchdowns

In [9]:
stats['Total Yards'] = tot_yards_stat #assign the lists to the columns 
stats['Total TDs'] = tot_td_stat
qb['Total Yards'] = tot_yards_qb #assign the lists to the columns 
qb['Total TDs'] = tot_td_qb

In [10]:
stats = stats.drop(total_yards_cols_st + total_td_st, axis = 1) #drop all the columns in these lists
qb = qb.drop(total_yards_cols_qb + total_td_qb, axis = 1) #drop all the columns in these lists

In [11]:
stats

,Player Id,Name,Year,Season,Home or Away,Week,Game Date,Opponent,Outcome,Total Yards,Total TDs
0,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Home,1,08/11,CHI,L,0.0,0.0
1,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Away,2,08/18,ARI,W,19.0,0.0
2,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Home,3,08/25,DAL,W,0.0,0.0
3,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Away,4,08/30,TB,L,134.0,0.0
4,billdemory/2512778,"Demory, Bill",1974,Regular Season,Away,1,09/15,KC,L,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
220535,torreysmith/2495459,"Smith, Torrey",2011,Postseason,Home,19,01/15,HOU,W,9.0,0.0
220536,torreysmith/2495459,"Smith, Torrey",2011,Postseason,Away,20,01/22,NE,L,82.0,1.0
220537,jahkeengilmore/2514905,"Gilmore, Jahkeen",2007,Preseason,Away,1,08/11,NYG,W,0.0,0.0
220538,jahkeengilmore/2514905,"Gilmore, Jahkeen",2007,Preseason,Away,2,08/17,PHI,L,0.0,0.0
220539,jahkeengilmore/2514905,"Gilmore, Jahkeen",2007,Preseason,Home,3,08/24,NE,L,0.0,0.0

In [12]:
qb

,Player Id,Name,Year,Season,Home or Away,Week,Game Date,Opponent,Outcome,Ints,Passer Rating,Total Yards,Total TDs
0,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Home,1,08/11,CHI,L,--,0.0,0.0,0.0
1,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Away,2,08/18,ARI,W,0,46.9,19.0,0.0
2,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Home,3,08/25,DAL,W,--,0.0,0.0,0.0
3,jaredzabransky/2495791,"Zabransky, Jared",2007,Preseason,Away,4,08/30,TB,L,1,50.8,134.0,0.0
4,billdemory/2512778,"Demory, Bill",1974,Regular Season,Away,1,09/15,KC,L,--,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40242,steveramsey/2523725,"Ramsey, Steve",1971,Regular Season,Home,12,12/05,CHI,W,2,25.3,81.0,0.0
40243,steveramsey/2523725,"Ramsey, Steve",1971,Regular Season,Away,13,12/12,SD,L,3,37.3,169.0,1.0
40244,steveramsey/2523725,"Ramsey, Steve",1971,Regular Season,Away,14,12/19,OAK,L,1,57.5,211.0,1.0
40245,steveramsey/2523725,"Ramsey, Steve",1970,Regular Season,Home,13,12/13,SF,L,--,0.0,0.0,0.0
40246,steveramsey/2523725,"Ramsey, Steve",1970,Regular Season,Home,14,12/20,CHI,L,0,39.6,0.0,0.0

In [13]:
qb = qb[qb["Year"] >= 2014] #only take rows with years 2014 and after
qb = qb[qb["Season"] != "Preseason"] #only take rows for regular season and postseason 
qb = qb[qb["Season"] != "Pro Bowl"]
qb['Season'] = qb['Season'].replace({'Regular Season':0, 'Postseason':1}) #create dummy varibales 
qb['Home or Away'] = qb['Home or Away'].replace({'Away':0, 'Home':1})
qb['Outcome'] = qb['Outcome'].astype('category')
#qb.isnull().sum() #check for nulls in the data

In [14]:
stats = stats[stats["Year"] >= 2014] #only take rows with years 2014 and after
stats = stats[stats["Season"] != "Preseason"] #only take rows for regular season and postseason 
stats = stats[stats["Season"] != "Pro Bowl"]
stats['Season'] = stats['Season'].replace({'Regular Season':0, 'Postseason':1}) #create dummy varibales 
stats['Home or Away'] = stats['Home or Away'].replace({'Away':0, 'Home':1})
stats['Outcome'] = stats['Outcome'].astype('category')
#stats.isnull().sum() #check for nulls in the data

###############################################################################

### Adding team_key to get the full team names for opponents:

In [3]:
team_key = pd.read_csv(r'team_key.csv')

In [16]:
stats_2 = stats.merge(team_key, how = "left", on = 'Opponent') #merge data to get full team names column for opponents
qb = qb.merge(team_key, how = "left", on = 'Opponent')

In [17]:
stats_2

,Player Id,Name,Year,Season,Home or Away,Week,Game Date,Opponent,Outcome,Total Yards,Total TDs,Opponent_full
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,09/11,CHI,W,0.0,0.0,Chicago Bears
1,tomsavage/2543640,"Savage, Tom",2016,0,1,2,09/18,KC,W,0.0,0.0,Kansas City Chiefs
2,tomsavage/2543640,"Savage, Tom",2016,0,0,3,09/22,NE,L,0.0,0.0,New England Patriots
3,tomsavage/2543640,"Savage, Tom",2016,0,1,4,10/02,TEN,W,0.0,0.0,Tennessee Titans
4,tomsavage/2543640,"Savage, Tom",2016,0,0,5,10/09,MIN,L,0.0,0.0,Minnesota Vikings
...,...,...,...,...,...,...,...,...,...,...,...,...
21166,torreysmith/2495459,"Smith, Torrey",2014,0,1,15,12/14,JAC,W,16.0,0.0,Jacksonville Jaguars
21167,torreysmith/2495459,"Smith, Torrey",2014,0,0,16,12/21,HOU,L,59.0,2.0,Houston Texans
21168,torreysmith/2495459,"Smith, Torrey",2014,0,1,17,12/28,CLE,W,83.0,1.0,Cleveland Browns
21169,torreysmith/2495459,"Smith, Torrey",2014,1,0,18,01/03,PIT,W,28.0,1.0,Pittsburgh Steelers
21170,torreysmith/2495459,"Smith, Torrey",2014,1,0,19,01/10,NE,L,62.0,0.0,New England Patriots

In [18]:
qb

,Player Id,Name,Year,Season,Home or Away,Week,Game Date,Opponent,Outcome,Ints,Passer Rating,Total Yards,Total TDs,Opponent_full
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,09/11,CHI,W,--,0.0,0.0,0.0,Chicago Bears
1,tomsavage/2543640,"Savage, Tom",2016,0,1,2,09/18,KC,W,--,0.0,0.0,0.0,Kansas City Chiefs
2,tomsavage/2543640,"Savage, Tom",2016,0,0,3,09/22,NE,L,--,0.0,0.0,0.0,New England Patriots
3,tomsavage/2543640,"Savage, Tom",2016,0,1,4,10/02,TEN,W,--,0.0,0.0,0.0,Tennessee Titans
4,tomsavage/2543640,"Savage, Tom",2016,0,0,5,10/09,MIN,L,--,0.0,0.0,0.0,Minnesota Vikings
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3575,brockosweiler/2533436,"Osweiler, Brock",2014,0,1,14,12/07,BUF,W,--,0.0,0.0,0.0,Buffalo Bills
3576,brockosweiler/2533436,"Osweiler, Brock",2014,0,0,15,12/14,SD,W,0,39.6,-1.0,0.0,San Diego Chargers
3577,brockosweiler/2533436,"Osweiler, Brock",2014,0,0,16,12/22,CIN,L,--,0.0,0.0,0.0,Cincinnati Bengals
3578,brockosweiler/2533436,"Osweiler, Brock",2014,0,1,17,12/28,OAK,W,0,158.3,38.0,1.0,Oakland Raiders
3579,brockosweiler/2533436,"Osweiler, Brock",2014,1,1,19,01/11,IND,L,--,0.0,0.0,0.0,Indianapolis Colts

In [19]:
#change column names to prepare for merge 
stats_2 = stats_2.drop(['Opponent'], axis = 1)
qb = qb.drop(['Opponent'], axis=1)
stats_2 = stats_2.rename(columns = {'Opponent_full':'Opponent'}) 
qb = qb.rename(columns = {'Opponent_full':'Opponent'})

###############################################################################

#### Adding QBR as another measure of produtivity for qb data:
<br><i>Note: this data was obtained from <a href='https://www.espn.com/nfl/qbr/_/view/weekly/season/2016/seasontype/2/week/1'> espn.com </a><br>Data was cleaned [here](./QBR_Clean.ipynb) </i>

In [4]:
qbr = pd.read_csv(r'qbr_clean.csv')

In [22]:
qbr = qbr.drop('Unnamed: 0', axis = 1)
qbr

                   Name  Week   QBR  Year
0     Kaepernick, Colin     1  95.3  2014
1     Stafford, Matthew     1  93.1  2014
2       Manning, Peyton     1  90.0  2014
3       Wilson, Russell     1  85.2  2014
4            Ryan, Matt     1  85.1  2014
...                 ...   ...   ...   ...
1593         Ryan, Matt    20  97.2  2016
1594         Brady, Tom    20  89.6  2016
1595     Rodgers, Aaron    20  86.1  2016
1596         Ryan, Matt    22  81.0  2016
1597         Brady, Tom    22  75.8  2016

[1598 rows x 4 columns]

In [23]:
qb = qb.merge(qbr, on = ['Year', 'Week', 'Name'], how = 'right')

In [24]:
qb

,Player Id,Name,Year,Season,Home or Away,Week,Game Date,Outcome,Ints,Passer Rating,Total Yards,Total TDs,Opponent,QBR
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,09/07,W,0,125.5,212.0,2.0,Dallas Cowboys,95.3
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,09/08,W,0,125.3,348.0,3.0,New York Giants,93.1
2,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,09/07,W,0,111.9,266.0,3.0,Indianapolis Colts,90.0
3,russellwilson/2532975,"Wilson, Russell",2014,0.0,1.0,1,09/04,W,0,110.9,220.0,2.0,Green Bay Packers,85.2
4,mattryan/310,"Ryan, Matt",2014,0.0,1.0,1,09/07,W,0,128.8,463.0,3.0,New Orleans Saints,85.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1593,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,01/22,W,0,139.4,415.0,5.0,Green Bay Packers,97.2
1594,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,01/22,W,0,127.5,383.0,3.0,Pittsburgh Steelers,89.6
1595,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,01/22,L,1,91.6,333.0,3.0,Atlanta Falcons,86.1
1596,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,02/05,L,0,144.1,284.0,2.0,New England Patriots,81.0
1597,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,02/05,W,1,95.2,481.0,2.0,Atlanta Falcons,75.8

#############################################################################################################################

#### Games Data:
<br><i>Note: this data was obtained from <a href='https://www.kaggle.com/datasets/sujaykapadnis/nfl-stadium-attendance-dataset?select=games.csv'> Kaggle.com </a><br> Data was cleaned [here](./Games_Clean.ipynb)</i>

In [5]:
games = pd.read_csv(r'games_cleaned.csv')

In [26]:
games.isnull().any()
games = games.drop('Unnamed: 0', axis = 1)

In [27]:
games

,Year,Week,Team,Opponent,Game Date,Time,Thursday Game
0,2014,1,Seattle Seahawks,Green Bay Packers,09/04,8:42PM,1
1,2014,1,St. Louis Rams,Minnesota Vikings,09/07,1:00PM,0
2,2014,1,Chicago Bears,Buffalo Bills,09/07,1:00PM,0
3,2014,1,Baltimore Ravens,Cincinnati Bengals,09/07,1:02PM,0
4,2014,1,Philadelphia Eagles,Jacksonville Jaguars,09/07,1:02PM,0
...,...,...,...,...,...,...,...
1597,2016,19,Green Bay Packers,Dallas Cowboys,1/15,4:40PM,0
1598,2016,19,Pittsburgh Steelers,Kansas City Chiefs,1/15,8:20PM,0
1599,2016,20,Green Bay Packers,Atlanta Falcons,1/22,3:05PM,0
1600,2016,20,Pittsburgh Steelers,New England Patriots,1/22,6:40PM,0
1601,2016,22,Atlanta Falcons,New England Patriots,2/5,6:30PM,0

In [28]:
#make sure that the merge columns are the same type otherwise an error will occur 
games['Week'] = pd.to_numeric(games['Week'], errors = 'coerce')
stats['Week'] = pd.to_numeric(stats['Week'], errors = 'coerce')

print(type(games['Week'][3]))
print(type(stats_2['Week'][7]))
print(type(qb['Week'][12]))
print(type(games['Game Date'][3]))
print(type(stats_2['Game Date'][7]))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>

In [29]:
stats_3 = stats_2.merge(games, on = ["Year",  'Opponent', 'Week'], how = 'left')

In [30]:
teams_index = stats_3['Team'].index[0:]
team_home = []
for i in teams_index:
    if stats_3['Home or Away'][i] == 1: 
        team_home.append(stats_3['Team'][i])
    else:
        team_home.append(stats_3['Opponent'][i])
stats_3['Home Team'] = team_home

In [31]:
stats_3 = stats_3.drop('Game Date_y', axis = 1)

In [32]:
#convert time data into categorical variable for primetime
print(type(stats_3["Time"][0]))

<class 'str'>

In [33]:
stat_index = stats_3.index[0:]
primetime = []
for num in stat_index:
    if stats_3["Season"][num] == 0.0:
        if stats_3['Time'][num].startswith(('1','3','4','6')):
            primetime.append(0)
        else:
            primetime.append(1)
    else: 
        primetime.append(1)
stats_3['Primetime'] = primetime
stats_3

,Player Id,Name,Year,Season,Home or Away,Week,Game Date_x,Outcome,Total Yards,Total TDs,Opponent,Team,Time,Thursday Game,Home Team,Primetime
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,09/11,W,0.0,0.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0
1,tomsavage/2543640,"Savage, Tom",2016,0,1,2,09/18,W,0.0,0.0,Kansas City Chiefs,Houston Texans,1:02PM,0,Houston Texans,0
2,tomsavage/2543640,"Savage, Tom",2016,0,0,3,09/22,L,0.0,0.0,New England Patriots,Houston Texans,8:26PM,1,New England Patriots,1
3,tomsavage/2543640,"Savage, Tom",2016,0,1,4,10/02,W,0.0,0.0,Tennessee Titans,Houston Texans,1:02PM,0,Houston Texans,0
4,tomsavage/2543640,"Savage, Tom",2016,0,0,5,10/09,L,0.0,0.0,Minnesota Vikings,Houston Texans,1:05PM,0,Minnesota Vikings,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21166,torreysmith/2495459,"Smith, Torrey",2014,0,1,15,12/14,W,16.0,0.0,Jacksonville Jaguars,Baltimore Ravens,1:02PM,0,Baltimore Ravens,0
21167,torreysmith/2495459,"Smith, Torrey",2014,0,0,16,12/21,L,59.0,2.0,Houston Texans,Baltimore Ravens,1:02PM,0,Houston Texans,0
21168,torreysmith/2495459,"Smith, Torrey",2014,0,1,17,12/28,W,83.0,1.0,Cleveland Browns,Baltimore Ravens,1:02PM,0,Baltimore Ravens,0
21169,torreysmith/2495459,"Smith, Torrey",2014,1,0,18,01/03,W,28.0,1.0,Pittsburgh Steelers,Baltimore Ravens,8:15PM,0,Pittsburgh Steelers,1
21170,torreysmith/2495459,"Smith, Torrey",2014,1,0,19,01/10,L,62.0,0.0,New England Patriots,Baltimore Ravens,4:35PM,0,New England Patriots,1

In [34]:
qb_2 = qb.merge(games,on = ["Year",  'Opponent', 'Week'], how = 'left')

In [35]:
teams_index = qb_2['Team'].index[0:]
team_home = []
for i in teams_index:
    if qb_2['Home or Away'][i] == 1: 
        team_home.append(qb_2['Team'][i])
    else:
        team_home.append(qb_2['Opponent'][i])
qb_2['Home Team'] = team_home

In [36]:
qb_2 = qb_2.drop('Game Date_y', axis = 1)

In [37]:
qb_2_index = qb_2.index[0:]
primetime = []
for num in qb_2_index:
    if qb_2["Season"][num] == 0.0:
        if qb_2['Time'][num].startswith(('1','3','4','6')):
            primetime.append(0)
        else:
            primetime.append(1)
    else: 
        primetime.append(1)
qb_2['Primetime'] = primetime

In [38]:

qb_2

,Player Id,Name,Year,Season,Home or Away,Week,Game Date_x,Outcome,Ints,Passer Rating,Total Yards,Total TDs,Opponent,QBR,Team,Time,Thursday Game,Home Team,Primetime
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,09/07,W,0,125.5,212.0,2.0,Dallas Cowboys,95.3,San Francisco 49ers,4:25PM,0.0,Dallas Cowboys,0
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,09/08,W,0,125.3,348.0,3.0,New York Giants,93.1,Detroit Lions,7:11PM,0.0,Detroit Lions,1
2,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,09/07,W,0,111.9,266.0,3.0,Indianapolis Colts,90.0,Denver Broncos,8:30PM,0.0,Denver Broncos,1
3,russellwilson/2532975,"Wilson, Russell",2014,0.0,1.0,1,09/04,W,0,110.9,220.0,2.0,Green Bay Packers,85.2,Seattle Seahawks,8:42PM,1.0,Seattle Seahawks,1
4,mattryan/310,"Ryan, Matt",2014,0.0,1.0,1,09/07,W,0,128.8,463.0,3.0,New Orleans Saints,85.1,Atlanta Falcons,1:03PM,0.0,Atlanta Falcons,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1593,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,01/22,W,0,139.4,415.0,5.0,Green Bay Packers,97.2,Atlanta Falcons,3:05PM,0.0,Atlanta Falcons,1
1594,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,01/22,W,0,127.5,383.0,3.0,Pittsburgh Steelers,89.6,New England Patriots,6:40PM,0.0,New England Patriots,1
1595,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,01/22,L,1,91.6,333.0,3.0,Atlanta Falcons,86.1,Green Bay Packers,3:05PM,0.0,Atlanta Falcons,1
1596,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,02/05,L,0,144.1,284.0,2.0,New England Patriots,81.0,Atlanta Falcons,6:30PM,0.0,Atlanta Falcons,1
1597,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,02/05,W,1,95.2,481.0,2.0,Atlanta Falcons,75.8,New England Patriots,6:30PM,0.0,Atlanta Falcons,1

###############################################################################
### Weather Data:
<br><i>Note: this data was obtained from <a href='https://www.kaggle.com/datasets/tobycrabtree/nfl-scores-and-betting-data?rvi=1&select=spreadspoke_scores.csv'> Kaggle.com </a><br> Data was cleaned [here](./Spread_Clean.ipynb)</i>

In [6]:
spread = pd.read_csv(r'spread_cleaned.csv')

In [41]:
spread = spread.drop('Unnamed: 0', axis = 1)

In [42]:
spread['Week'] = pd.to_numeric(spread['Week'], errors = 'coerce')
print(type(spread['Week'][7]))
print(type(stats_3['Week'][7]))

<class 'numpy.int64'>
<class 'numpy.int64'>

In [43]:
stats_4 = stats_3.merge(spread, on=['Week','Year', 'Season', 'Home Team'], how='inner')
stats_4 = stats_4.drop('Game Date_x', axis = 1)
stats_4

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Total Yards,Total TDs,Opponent,Team,Time,Thursday Game,Home Team,Primetime,Game Date,Away Team,weather_temperature,weather_wind_mph
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,W,0.0,0.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0
1,brandonweeden/2532970,"Weeden, Brandon",2016,0,1,1,W,0.0,0.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0
2,jaycutler/2495824,"Cutler, Jay",2016,0,0,1,L,228.0,1.0,Houston Texans,Chicago Bears,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0
3,brianhoyer/81294,"Hoyer, Brian",2016,0,0,1,L,0.0,0.0,Houston Texans,Chicago Bears,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0
4,brockosweiler/2533436,"Osweiler, Brock",2016,0,1,1,W,245.0,2.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21166,jeremymaclin/80429,"Maclin, Jeremy",2014,0,1,12,W,59.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0
21167,jeffmaehl/2530713,"Maehl, Jeff",2014,0,1,12,W,0.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0
21168,richardgordon/2499255,"Gordon, Richard",2014,0,0,12,L,0.0,0.0,Philadelphia Eagles,Tennessee Titans,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0
21169,brentcelek/2507218,"Celek, Brent",2014,0,1,12,W,48.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0
21170,joshhuff/2543746,"Huff, Josh",2014,0,1,12,W,0.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0

In [44]:
stats_4.isnull().sum()

Player Id              0
Name                   0
Year                   0
Season                 0
Home or Away           0
Week                   0
Outcome                0
Total Yards            0
Total TDs              0
Opponent               0
Team                   0
Time                   0
Thursday Game          0
Home Team              0
Primetime              0
Game Date              0
Away Team              0
weather_temperature    0
weather_wind_mph       0
dtype: int64

In [45]:
stats_4 = stats_4.rename(columns = {'weather_temperature':'Weather Temp', 'weather_wind_mph':'Weather MPH'})

In [46]:
qb_3 = qb_2.merge(spread, on=['Week','Year', 'Season', 'Home Team'], how='inner')
qb_3 = qb_3.drop('Game Date_x', axis = 1)
qb_3

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Ints,Passer Rating,Total Yards,...,QBR,Team,Time,Thursday Game,Home Team,Primetime,Game Date,Away Team,weather_temperature,weather_wind_mph
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,W,0,125.5,212.0,...,95.3,San Francisco 49ers,4:25PM,0.0,Dallas Cowboys,0,9/7/2014,San Francisco 49ers,72.0,0.0
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,W,0,125.3,348.0,...,93.1,Detroit Lions,7:11PM,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0
2,elimanning/2505996,"Manning, Eli",2014,0.0,0.0,1,L,2,53.0,163.0,...,39.6,New York Giants,7:11PM,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0
3,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,W,0,111.9,266.0,...,90.0,Denver Broncos,8:30PM,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0
4,andrewluck/2533031,"Luck, Andrew",2014,0.0,0.0,1,L,2,83.1,389.0,...,46.9,Indianapolis Colts,8:30PM,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1473,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,W,0,139.4,415.0,...,97.2,Atlanta Falcons,3:05PM,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0
1474,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,L,1,91.6,333.0,...,86.1,Green Bay Packers,3:05PM,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0
1475,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,W,0,127.5,383.0,...,89.6,New England Patriots,6:40PM,0.0,New England Patriots,1,1/22/2017,Pittsburgh Steelers,41.0,10.0
1476,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,L,0,144.1,284.0,...,81.0,Atlanta Falcons,6:30PM,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0
1477,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,W,1,95.2,481.0,...,75.8,New England Patriots,6:30PM,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0

In [47]:
qb_3 = qb_3.rename(columns = {'weather_temperature':'Weather Temp', 'weather_wind_mph':'Weather MPH'})

In [48]:
qb_3.isnull().sum()

Player Id        0
Name             0
Year             0
Season           0
Home or Away     0
Week             0
Outcome          0
Ints             0
Passer Rating    0
Total Yards      0
Total TDs        0
Opponent         0
QBR              0
Team             0
Time             0
Thursday Game    0
Home Team        0
Primetime        0
Game Date        0
Away Team        0
Weather Temp     0
Weather MPH      0
dtype: int64

##############################################################################

### Attendance data:
<br><i>Note: Data obtained from <a href='https://www.kaggle.com/datasets/sujaykapadnis/nfl-stadium-attendance-dataset'>Kaggle.com</a><br>Null values in the original data were replaced with the average attendance over the course of the three seasons used.<br>The original dataset did not include stadium attendance for playoff games. This data was obtained <a href='https://en.wikipedia.org/wiki/2014%E2%80%9315_NFL_playoffs'>here</a>.<br>The data imported was cleaned [here](./Attendace_Clean.ipynb)</i>

In [7]:
attendance = pd.read_csv(r'attendance_cleaned.csv')

In [50]:
attendance = attendance.drop('Unnamed: 0', axis = 1)

In [51]:
print(type(attendance['Week'][7]))
print(type(stats_4['Week'][7]))

<class 'numpy.int64'>
<class 'numpy.int64'>

In [52]:
stats_5 = stats_4.merge(attendance, on = ["Team", "Week", "Year"], how = 'left')
stats_5

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Total Yards,Total TDs,Opponent,Team,Time,Thursday Game,Home Team,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,W,0.0,0.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0
1,brandonweeden/2532970,"Weeden, Brandon",2016,0,1,1,W,0.0,0.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0
2,jaycutler/2495824,"Cutler, Jay",2016,0,0,1,L,228.0,1.0,Houston Texans,Chicago Bears,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0
3,brianhoyer/81294,"Hoyer, Brian",2016,0,0,1,L,0.0,0.0,Houston Texans,Chicago Bears,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0
4,brockosweiler/2533436,"Osweiler, Brock",2016,0,1,1,W,245.0,2.0,Chicago Bears,Houston Texans,1:05PM,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21166,jeremymaclin/80429,"Maclin, Jeremy",2014,0,1,12,W,59.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0
21167,jeffmaehl/2530713,"Maehl, Jeff",2014,0,1,12,W,0.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0
21168,richardgordon/2499255,"Gordon, Richard",2014,0,0,12,L,0.0,0.0,Philadelphia Eagles,Tennessee Titans,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0
21169,brentcelek/2507218,"Celek, Brent",2014,0,1,12,W,48.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0
21170,joshhuff/2543746,"Huff, Josh",2014,0,1,12,W,0.0,0.0,Tennessee Titans,Philadelphia Eagles,1:02PM,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0

In [53]:
qb_4 = qb_3.merge(attendance, on = ["Team", "Week", "Year"], how = 'left')
qb_4

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Ints,Passer Rating,Total Yards,...,Team,Time,Thursday Game,Home Team,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,W,0,125.5,212.0,...,San Francisco 49ers,4:25PM,0.0,Dallas Cowboys,0,9/7/2014,San Francisco 49ers,72.0,0.0,91174.0
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,W,0,125.3,348.0,...,Detroit Lions,7:11PM,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0,64401.0
2,elimanning/2505996,"Manning, Eli",2014,0.0,0.0,1,L,2,53.0,163.0,...,New York Giants,7:11PM,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0,64401.0
3,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,W,0,111.9,266.0,...,Denver Broncos,8:30PM,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0
4,andrewluck/2533031,"Luck, Andrew",2014,0.0,0.0,1,L,2,83.1,389.0,...,Indianapolis Colts,8:30PM,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1473,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,W,0,139.4,415.0,...,Atlanta Falcons,3:05PM,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0
1474,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,L,1,91.6,333.0,...,Green Bay Packers,3:05PM,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0
1475,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,W,0,127.5,383.0,...,New England Patriots,6:40PM,0.0,New England Patriots,1,1/22/2017,Pittsburgh Steelers,41.0,10.0,66829.0
1476,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,L,0,144.1,284.0,...,Atlanta Falcons,6:30PM,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0,70807.0
1477,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,W,1,95.2,481.0,...,New England Patriots,6:30PM,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0,70807.0

###############################################################################

### Salary Data <br>
<i>Note:This data is from <a href='https://www.kaggle.com/datasets/f4k25g/nfl-salaries?rvi=1'>Kaggle.com</a><br>Data was cleaned [here](./Salary_Clean.ipynb)</i>

In [8]:
salary = pd.read_csv(r'salary_clean.csv')

In [55]:
salary = salary.drop('Unnamed: 0', axis = 1)

In [56]:
stats_6 = stats_5.merge(salary, on = ["Name", "Year", "Team"], how = "left")
stats_6

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Total Yards,Total TDs,Opponent,...,Thursday Game,Home Team,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance,Salary,Cap Percentage
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,W,0.0,0.0,Chicago Bears,...,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,675146.0,0.43
1,brandonweeden/2532970,"Weeden, Brandon",2016,0,1,1,W,0.0,0.0,Chicago Bears,...,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,1737500.0,1.11
2,jaycutler/2495824,"Cutler, Jay",2016,0,0,1,L,228.0,1.0,Houston Texans,...,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,NaN,NaN
3,brianhoyer/81294,"Hoyer, Brian",2016,0,0,1,L,0.0,0.0,Houston Texans,...,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,NaN,NaN
4,brockosweiler/2533436,"Osweiler, Brock",2016,0,1,1,W,245.0,2.0,Chicago Bears,...,0,Houston Texans,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,12000000.0,7.63
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21166,jeremymaclin/80429,"Maclin, Jeremy",2014,0,1,12,W,59.0,0.0,Tennessee Titans,...,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,5468750.0,3.66
21167,jeffmaehl/2530713,"Maehl, Jeff",2014,0,1,12,W,0.0,0.0,Tennessee Titans,...,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,570000.0,0.38
21168,richardgordon/2499255,"Gordon, Richard",2014,0,0,12,L,0.0,0.0,Philadelphia Eagles,...,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,NaN,NaN
21169,brentcelek/2507218,"Celek, Brent",2014,0,1,12,W,48.0,0.0,Tennessee Titans,...,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,4075000.0,2.73
21170,joshhuff/2543746,"Huff, Josh",2014,0,1,12,W,0.0,0.0,Tennessee Titans,...,0,Philadelphia Eagles,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,558986.0,0.37

In [57]:
qb_5 = qb_4.merge(salary, on = ["Name", "Year", "Team"], how = "left")
qb_5

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Ints,Passer Rating,Total Yards,...,Thursday Game,Home Team,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance,Salary,Cap Percentage
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,W,0,125.5,212.0,...,0.0,Dallas Cowboys,0,9/7/2014,San Francisco 49ers,72.0,0.0,91174.0,3767444.0,2.78
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,W,0,125.3,348.0,...,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0,64401.0,15820000.0,11.96
2,elimanning/2505996,"Manning, Eli",2014,0.0,0.0,1,L,2,53.0,163.0,...,0.0,Detroit Lions,1,9/8/2014,New York Giants,72.0,0.0,64401.0,20400000.0,15.45
3,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,W,0,111.9,266.0,...,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0,17500000.0,12.96
4,andrewluck/2533031,"Luck, Andrew",2014,0.0,0.0,1,L,2,83.1,389.0,...,0.0,Denver Broncos,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0,6029454.0,4.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1473,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,W,0,139.4,415.0,...,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0,23750000.0,14.96
1474,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,L,1,91.6,333.0,...,0.0,Atlanta Falcons,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0,19250000.0,11.78
1475,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,W,0,127.5,383.0,...,0.0,New England Patriots,1,1/22/2017,Pittsburgh Steelers,41.0,10.0,66829.0,13764705.0,8.62
1476,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,L,0,144.1,284.0,...,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0,70807.0,23750000.0,14.96
1477,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,W,1,95.2,481.0,...,0.0,Atlanta Falcons,1,2/5/2017,New England Patriots,72.0,0.0,70807.0,13764705.0,8.62

In [58]:
qb_5 = qb_5.dropna()
stats_6 = stats_6.dropna()

In [59]:
##############################################################################

### Height and weight info<br>
<i>Note: This data came from <a href='https://www.kaggle.com/datasets/kendallgillies/nflstatistics?rvi=1'>Kaggle.com</a>

In [60]:
basic_info = pd.read_excel("Basic_Stats.xlsx", sheet_name="Basic_Stats")

In [61]:
basic_info.columns

Index(['Age', 'Birth Place', 'Birthday', 'College', 'Current Status',
       'Current Team', 'Experience', 'Height (inches)', 'High School',
       'High School Location', 'Name', 'Number', 'Player Id', 'Position',
       'Weight (lbs)', 'Years Played'],
      dtype='object')

In [62]:
basic_info = basic_info[['Weight (lbs)', 'Height (inches)', 'Player Id']] #pull columns that could be used

In [63]:
stats_7 = stats_6.merge(basic_info, on = 'Player Id', how ='left')
stats_7

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Total Yards,Total TDs,Opponent,...,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance,Salary,Cap Percentage,Weight (lbs),Height (inches)
0,tomsavage/2543640,"Savage, Tom",2016,0,1,1,W,0.0,0.0,Chicago Bears,...,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,675146.0,0.43,230.0,76.0
1,brandonweeden/2532970,"Weeden, Brandon",2016,0,1,1,W,0.0,0.0,Chicago Bears,...,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,1737500.0,1.11,230.0,76.0
2,brockosweiler/2533436,"Osweiler, Brock",2016,0,1,1,W,245.0,2.0,Chicago Bears,...,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,12000000.0,7.63,235.0,80.0
3,jayprosch/2543695,"Prosch, Jay",2016,0,1,1,W,2.0,0.0,Chicago Bears,...,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,619670.0,0.39,255.0,73.0
4,lamarmiller/2533034,"Miller, Lamar",2016,0,1,1,W,117.0,0.0,Chicago Bears,...,0,9/11/2016,Chicago Bears,87.0,2.0,71933.0,5500000.0,3.50,220.0,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18450,kendallwright/2532977,"Wright, Kendall",2014,0,0,12,L,28.0,0.0,Philadelphia Eagles,...,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,2241396.0,1.61,191.0,70.0
18451,jeremymaclin/80429,"Maclin, Jeremy",2014,0,1,12,W,59.0,0.0,Tennessee Titans,...,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,5468750.0,3.66,198.0,72.0
18452,jeffmaehl/2530713,"Maehl, Jeff",2014,0,1,12,W,0.0,0.0,Tennessee Titans,...,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,570000.0,0.38,184.0,72.0
18453,brentcelek/2507218,"Celek, Brent",2014,0,1,12,W,48.0,0.0,Tennessee Titans,...,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,4075000.0,2.73,255.0,76.0
18454,joshhuff/2543746,"Huff, Josh",2014,0,1,12,W,0.0,0.0,Tennessee Titans,...,0,11/23/2014,Tennessee Titans,53.0,6.0,69596.0,558986.0,0.37,206.0,71.0

In [64]:
qb_6 = qb_5.merge(basic_info, on = 'Player Id', how ='left')
qb_6

,Player Id,Name,Year,Season,Home or Away,Week,Outcome,Ints,Passer Rating,Total Yards,...,Primetime,Game Date,Away Team,Weather Temp,Weather MPH,Attendance,Salary,Cap Percentage,Weight (lbs),Height (inches)
0,colinkaepernick/2495186,"Kaepernick, Colin",2014,0.0,0.0,1,W,0,125.5,212.0,...,0,9/7/2014,San Francisco 49ers,72.0,0.0,91174.0,3767444.0,2.78,230.0,76.0
1,matthewstafford/79860,"Stafford, Matthew",2014,0.0,1.0,1,W,0,125.3,348.0,...,1,9/8/2014,New York Giants,72.0,0.0,64401.0,15820000.0,11.96,226.0,75.0
2,elimanning/2505996,"Manning, Eli",2014,0.0,0.0,1,L,2,53.0,163.0,...,1,9/8/2014,New York Giants,72.0,0.0,64401.0,20400000.0,15.45,218.0,76.0
3,peytonmanning/2501863,"Manning, Peyton",2014,0.0,1.0,1,W,0,111.9,266.0,...,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0,17500000.0,12.96,230.0,77.0
4,andrewluck/2533031,"Luck, Andrew",2014,0.0,0.0,1,L,2,83.1,389.0,...,1,9/7/2014,Indianapolis Colts,70.0,6.0,76939.0,6029454.0,4.52,240.0,76.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,mattryan/310,"Ryan, Matt",2016,1.0,1.0,20,W,0,139.4,415.0,...,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0,23750000.0,14.96,217.0,76.0
1393,aaronrodgers/2506363,"Rodgers, Aaron",2016,1.0,0.0,20,L,1,91.6,333.0,...,1,1/22/2017,Green Bay Packers,72.0,0.0,71127.0,19250000.0,11.78,225.0,74.0
1394,tombrady/2504211,"Brady, Tom",2016,1.0,1.0,20,W,0,127.5,383.0,...,1,1/22/2017,Pittsburgh Steelers,41.0,10.0,66829.0,13764705.0,8.62,225.0,76.0
1395,mattryan/310,"Ryan, Matt",2016,1.0,1.0,22,L,0,144.1,284.0,...,1,2/5/2017,New England Patriots,72.0,0.0,70807.0,23750000.0,14.96,217.0,76.0
1396,tombrady/2504211,"Brady, Tom",2016,1.0,0.0,22,W,1,95.2,481.0,...,1,2/5/2017,New England Patriots,72.0,0.0,70807.0,13764705.0,8.62,225.0,76.0

In [65]:
qb_6.isnull().sum()

Player Id          0
Name               0
Year               0
Season             0
Home or Away       0
Week               0
Outcome            0
Ints               0
Passer Rating      0
Total Yards        0
Total TDs          0
Opponent           0
QBR                0
Team               0
Time               0
Thursday Game      0
Home Team          0
Primetime          0
Game Date          0
Away Team          0
Weather Temp       0
Weather MPH        0
Attendance         0
Salary             0
Cap Percentage     0
Weight (lbs)       0
Height (inches)    0
dtype: int64

In [66]:
stats_7.isnull().sum()

Player Id          0
Name               0
Year               0
Season             0
Home or Away       0
Week               0
Outcome            0
Total Yards        0
Total TDs          0
Opponent           0
Team               0
Time               0
Thursday Game      0
Home Team          0
Primetime          0
Game Date          0
Away Team          0
Weather Temp       0
Weather MPH        0
Attendance         0
Salary             0
Cap Percentage     0
Weight (lbs)       0
Height (inches)    0
dtype: int64

In [67]:
stats_7.to_csv('Final_Data_Skills_Players.csv')

In [68]:
qb_6.to_csv('Final_Data_qbs.csv')